# Data manipulation

## Tensors

In [123]:
import torch

In [124]:
x = torch.arange(12, dtype=torch.float32) # vector (1D tensor)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [125]:
print(f"""
end exclusive

{torch.arange(end=5)}
{torch.arange(5)}
{torch.arange(start=1, end=10)}
{torch.arange(start=1, end=10, step=2)}
{torch.arange(start=0, end=10, step=2)}
""")


end exclusive

tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])
tensor([0, 2, 4, 6, 8])



In [126]:
x.numel() # number of elements

12

In [127]:
x.shape # size along each axis

torch.Size([12])

In [128]:
X = x.reshape(3, 4) # reshape vector into a matrix (2D tensor)
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


Lahko ugotovi, kateri dimenzije so primerne, če mu podamo velikost samo ene smeri.

-1 podamo tam, kjer naj sam ugotovi iz števila elementov in druge podane smeri.

In [129]:
print(x.reshape(-1, 4))
print(x.reshape(3, -1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [130]:
print(torch.zeros(3, 4)) # matrix of zeros
print(torch.ones(4, 3)) # matrix of ones


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


`randn` randomly sampla vrednosti iz normalne porazdelitve (mean = 0, std = 1).

In [131]:
print(torch.randn(3, 4))

tensor([[-1.1320, -0.1156, -0.2125, -0.7168],
        [ 0.2373, -0.1095,  1.3252,  0.3607],
        [ 2.1485,  0.6303, -0.3436,  0.4808]])


In [132]:
print(torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])) # explicitly set values from python array

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


## Operations

In [133]:
X[:2, :] = 12 # spremeni range elementov; v tem primeru vse vrstice pred drugo (0-based) in vse stolpce
print(X)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


*Elementwise* scalar operations: operacije ki se izvedejo na vseh elemenitih. Preslikava ki vsak element preslika v nekaj.

In [134]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

*Binary* scalar operations: operacije ki preslikajo vektorski par (enakih velikosti) v nek skalar.

In [135]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

(x + y,
 x - y,
 x * y,
 x / y,
 x ** y)

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Konkatenacija dveh vektorjev. Podamo po kateri *axis* (dim) naj ju zlepi skupaj.
dim=0 pomeni po vrsticah, dim=1 pomeni po stolpcih.

In [136]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(torch.cat((X, Y), dim=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


In [137]:
print(torch.cat((X, Y), dim=1))

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [138]:
print(X == Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [139]:
X.sum()

tensor(66.)

## Conversion between python objects

In [140]:
A = X.numpy()
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [141]:
B = torch.from_numpy(A)
print(B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [142]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [143]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a) # dela samo za size-1 tensors

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.8. Exercises

Run the code in this section.

1. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.
2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [144]:
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [145]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [146]:
print(a + b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


V bistvu se $a$ podaljša po stolpcih, $b$ pa po vrsticah.

In [147]:
aa = torch.tensor([[0,0],
                   [1,1],
                   [2,2]])
bb = torch.tensor([[0,1],
                   [0,1],
                   [0,1]])
print(aa + bb)

tensor([[0, 1],
        [1, 2],
        [2, 3]])
