# Linear algebra

- Oftentimes, the word “dimension” gets overloaded to mean both the number of axes and the length along a particular axis.
  To avoid this confusion, we use **order** to refer to the number of axes and **dimensionality** exclusively to refer to the number of components.

In [1]:
import torch

In [2]:
A = torch.arange(6).reshape(3, 2)
print(A)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
print(A.T) # transposed A

tensor([[0, 2, 4],
        [1, 3, 5]])


3rd-order tensors so pomembni za image processing - height, width, channel (intenzitete red, blue in green barv). Še več, kolekcija slik je zapakirana v 4th-order tensorju,
kjer so posamezne slike razporejene vzdolž prve osi.

In [4]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Reduction

In [5]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [6]:
A.sum(axis=0), A.sum(axis=0).shape #axis=0 da naredi vsoto columnwise

(tensor([3., 5., 7.]), torch.Size([3]))

In [7]:
A.sum(axis=1), A.sum(axis=1).shape #axis=1 da naredi vsoto rowwise

(tensor([ 3., 12.]), torch.Size([2]))

In [8]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [9]:
A.mean() == A.sum() / A.numel()

tensor(True)

In [10]:
A.mean(axis=0), A.mean(axis=1)

(tensor([1.5000, 2.5000, 3.5000]), tensor([1., 4.]))

## Non-reduction sum

Sometimes it can be useful to keep the number of axes unchanged when invoking the function for calculating the sum or mean.
This matters when we want to use the broadcast mechanism.

In [11]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

For instance, since sum_A keeps its two axes after summing each row, we can divide A by sum_A with broadcasting to create a matrix
where each row sums up to 1.

In [12]:
print(A / sum_A)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])


## Dot-products

In [13]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y) # 0x1+1x1+2x1=3

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

Equivalently, we can calculate the dot product of two vectors by performing an elementwise multiplication followed by a sum:

In [14]:
torch.sum(x * y)

tensor(3.)

## Matrix-vector product

A's column count must be the same as x's length.

In [15]:
A.shape, x.shape, torch.mv(A, x), A@x # mv=matrix-vector

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## Matrix-matrix multiplication

Since A has shape [2,3], B must be of shape [3,n] for multiplication to be defined.

In [16]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B # mm = matrix-matrix

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))